version: 2.1

jobs:
  build:
    docker:
      - image: 'python:3.10'
    steps:
      - checkout
      - run:
          name: Check commit message
          command: ./scripts/check_commit.sh
      - run:
          name: Download pylint
          command: pip install pylint
      - run:
          name: Run pylint
          command: ./scripts/run_pylint_analysis.sh
  script-checker:
    docker:
      - image: 'python:3.10'
    steps:
      - checkout
      - run:
          name: Check file line count
          command: ./scripts/line_checker.sh

workflows:
  build_and_test:
    jobs:
      - build
      - script-checker
