version: 2.1

jobs:
  shubh-build:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: pip install poetry
      - run:
          name: Clear poetry cache
          command: poetry cache clear --all
      - run:
          name: Updating poetry
          command: pip install --upgrade poetry
      - run:
          name: Install Dependencies
          command: poetry install
      - run:
          name: Run Tests
          command: poetry run pytest

workflows:
  build_and_test:
    jobs:
      - shubh-build
