version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: pip install poetry
      - run:
          name: Install Dependencies
          command: poetry install -vvv

workflows:
  build_and_test:
    jobs:
      - build
