version: 2.1

jobs:
  build:
    docker:
      - image: 'python:3.10'
    steps:
      - checkout
      - run:
          name: Check commit message
          command: ./scripts/check_commit.sh

workflows:
  build_and_test:
    jobs:
      - build
